### ISSUE TITLE
在linux上做client不能正常使用

### ISSUE THREAD

**Issue by ricesin888** [neevek/rsproxy#2]
在centos 7中做client 配置， 外部程序将数据包发到socks5端口是没有再转发到TunnelOut,   但是，外部程序将数据包只要把数据包直接发到TunnelOut就可以正常使用。windows, mac os 是一切正常。

**Comment by neevek** [comment]
> 在centos 7中做client 配置， 外部程序将数据包发到socks5端口是没有再转发到TunnelOut, 但是，外部程序将数据包只要把数据包直接发到TunnelOut就可以正常使用。windows, mac os 是一切正常。

0.4.2 上用 socks5 作为入口需要明确使用 `socks5://` 协议，默认不写协议只支持 `http`，最新代码不需要指定，不过最新代码得自己 build，新版本应该晚些时候在会发。
